# Generated by Django 3.2.6 on 2021-12-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'Phòng tiêu chuẩn giường đôi (Standard Double Room)'), ('NAC', 'Phòng tiêu chuẩn 2 giường (Standard Twin Room)\t'), ('DEL', 'Phòng gia đình (Family Room)')], max_length=100),
        ),
    ]
