# Generated by Django 3.2.6 on 2021-12-06 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motel',
            fields=[
                ('motel_id', models.IntegerField(db_column='MOTEL_ID', primary_key=True, serialize=False)),
                ('motel_name', models.CharField(blank=True, db_column='MOTEL_NAME', max_length=100, null=True)),
                ('motel_label', models.CharField(blank=True, db_column='MOTEL_LABEL', max_length=100, null=True)),
                ('motel_address', models.CharField(blank=True, db_column='MOTEL_ADDRESS', max_length=100, null=True)),
                ('motel_location', models.CharField(blank=True, db_column='MOTEL_LOCATION', max_length=100, null=True)),
                ('motel_rating', models.IntegerField(blank=True, db_column='MOTEL_RATING', null=True)),
                ('motel_area', models.TextField(blank=True, db_column='MOTEL_AREA', null=True)),
                ('motel_price', models.IntegerField(blank=True, db_column='MOTEL_PRICE', null=True)),
                ('motel_content', models.TextField(blank=True, db_column='MOTEL_CONTENT', null=True)),
                ('motel_views', models.IntegerField(blank=True, db_column='MOTEL_VIEWS', null=True)),
                ('motel_image', models.TextField(blank=True, db_column='MOTEL_IMAGE', null=True)),
                ('motel_price_2', models.TextField(blank=True, db_column='MOTEL_PRICE_2', null=True)),
                ('motel_views_2', models.TextField(blank=True, db_column='MOTEL_VIEWS_2', null=True)),
            ],
            options={
                'db_table': 'motel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewsMotel',
            fields=[
                ('re_id', models.IntegerField(db_column='RE_ID', primary_key=True, serialize=False)),
                ('re_motel_rating1', models.IntegerField(blank=True, db_column='RE_MOTEL_RATING1', null=True)),
                ('re_motel_reviews', models.TextField(blank=True, db_column='RE_MOTEL_REVIEWS', null=True)),
            ],
            options={
                'db_table': 'reviews_motel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('star', models.IntegerField(db_column='star')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
