# Generated by Django 3.2.6 on 2021-11-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noidungkhachsan', '0003_auto_20211105_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenthotel',
            name='ratingstar',
        ),
    ]
