# Generated by Django 3.2.6 on 2021-11-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noidungkhachsan', '0004_remove_commenthotel_ratingstar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commenthotel',
            old_name='author1',
            new_name='author',
        ),
    ]
