# Generated by Django 3.2.6 on 2021-12-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noidungkhachsan', '0005_rename_author1_commenthotel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenthotel',
            name='ratingstar',
            field=models.IntegerField(db_column='ratingstar', default=1),
        ),
    ]
