# Generated by Django 3.2.6 on 2021-10-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dangnhapdangky', '0002_delete_usercustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=40, null=True)),
                ('user_email', models.CharField(blank=True, db_column='USER_EMAIL', max_length=100, null=True)),
                ('user_pass', models.CharField(blank=True, db_column='USER_PASS', max_length=20, null=True)),
                ('user_phone', models.CharField(blank=True, db_column='USER_PHONE', max_length=11, null=True)),
                ('user_address', models.CharField(blank=True, db_column='USER_ADDRESS', max_length=1024, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
